### ISSUE TITLE
This one's done great, but

### ISSUE THREAD

**Issue by BeanGTA** [PetteriM1/Nukkit-SuomiCraftPE#17]
I commented that this was supposed to be the original of nukkit. It is not supported much and many bugs I found. Do you know if you want me to find out the full flaw of this full nukkit?

I confirm that, your nukkit is wonderful

**Comment by PetteriM1** [comment]
Thanks. This Nukkit version is made for my server and its passed with code from NukkitX, old Nukkit and my own. The goal is to add more survival features and better stability and plugin support than NukkitX. You can send feature requests or bug reports here or to me with Discord private message if you want. I will close this since this is not an issue.
